[build]
builder = "Dockerfile"

[deploy]
startCommand = "node index.js"

[network]
internal = true
external = true # Bot needs to expose /qr for your browser

[build]
builder = "Docker"

[services.backend]
path = "backend"
env = "python"

[services.bot]
path = "bot"
env = "node"

[services.dashboard]
path = "dashboard"
env = "node"

