[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
startCommand = ""

[network]
internal = true
external = true # Bot needs to expose /qr for your browser

[services.backend]
path = "backend"
dockerfile = "Dockerfile"

[services.bot]
path = "bot"
dockerfile = "Dockerfile"

